name: Update FMHY Retype
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update:
    name: Update FMHY Retype
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Pull FMHYedit
        uses: actions/checkout@v2
        with:
          repository: nbats/FMHYedit
          path: FMHYedit
          
      - name: Move Files
        run: |
          mv FMHYedit ../FMHYedit
          cp README.md ../FMHYedit
          cp retype.yml ../FMHYedit
          cp -r static/ ../FMHYedit
        shell: bash
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Prepare Files
        shell: bash
        run: |
          cd ../FMHYedit
          python $GITHUB_WORKSPACE/replace-links-to-fmhy-in-files-in-current-dir.py
          python $GITHUB_WORKSPACE/add-headers.py

      - name: Build Retype
        uses: retypeapp/action-build@latest
        id: build
        with:
          config: ../FMHYedit

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
