name: Update FMHY Retype
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update:
    name: Update FMHY Retype
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Pull FMHYedit
        uses: actions/checkout@v2
        with:
          repository: nbats/FMHYedit
          path: FMHYedit
          
      - run: |
        mv FMHYedit ../FMHYedit
        cp README.md ../FMHYedit
        cp retype.yml ../FMHYedit
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Run Script
        shell: bash
        run: |
          cd ../FMHYedit
          echo "Y" | python $GITHUB_WORKSPACE/replace-links-to-fmhy-in-files-in-current-dir.py
          python $GITHUB_WORKSPACE/replace-links-to-fmhy-in-files-in-current-dir.py

      - uses: retypeapp/action-build@latest
        id: build
        with:
          config: ../FMHYedit

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
